### ISSUE TITLE
Cleanup FavoriteFragment

### ISSUE THREAD

**Issue by LarryAsante** [GrinnellAppDev/KDIC-Radio-Android#36]
This [class](https://github.com/GrinnellAppDev/KDIC-Radio-Android/blob/develop/app/src/main/java/edu/grinnell/kdic/FavoritesFragment.java) needs to be cleaned up a bit.

Goals :
* Make sure you recycle all non-UI member variables in Fragment#onDestroy() by nullifying them or calling their recycle methods (if any)
* Put all the resource strings into `strings.xml`
* Remove unused code (eg. TAG)

**Comment by LarryAsante** [comment]
@xtrajacoby Updates?

**Comment by xtrajacoby** [comment]
Im done!

**Comment by LarryAsante** [comment]
@xtrajacoby You wanna send a PR so I can check it?

**Comment by xtrajacoby** [comment]
Hey for some reason when I try to create a pull request I keep getting this error message.


Can't Create Pull Request
Push failed:
unable to access 'https://github.com/GrinnellAppDev/KDIC-Radio-Android.git/': The requested URL returned error: 403



________________________________

**Comment by LarryAsante** [comment]
Ah 403. It is forbidding you to push anything to the repository probably b/c I haven't added you as a contributor. Let me fix that.

**Comment by LarryAsante** [comment]
@xtrajacoby First, check your email for the confirmation that I added you as a collaborator. If you got that, try pushing it again. Let me know if it doesn't work

**Comment by xtrajacoby** [comment]
Alright let me know when you fix it and I'll do a pull request!

Jacob

**Comment by LarryAsante** [comment]
@xtrajacoby You should try it now!

**Comment by xtrajacoby** [comment]
I'm still getting this error message:

5:54 PM Can't Create Pull Request
Push failed:
failed to push some refs to 'https://github.com/GrinnellAppDev/KDIC-Radio-Android.git'


________________________________

**Comment by LarryAsante** [comment]
Well, looks like our initial problem is fixed. This is a different thing. First, `pull` the repository so you're in sync. Next, create a branch for your work and push your current changes to that branch. Finally, send a pull request and tag me and @PsychicNoodles, @YazanKittaneh or @prabirmsp in it
